# Generated by Django 5.2.1 on 2025-05-27 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0002_blog_image_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, default='Blog/media/blog_images/empty_blog.png', null=True, upload_to='blog_images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='Blog/media/post_images/empty_post.png', null=True, upload_to='post_images/'),
        ),
    ]
