# Generated by Django 5.2.1 on 2025-05-27 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0004_alter_blog_image_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nickname',
            field=models.CharField(default='Guest', max_length=255),
        ),
    ]
